### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by gbouteiller** [diggy/polylang-cli#32]
Hello,
First of all, thank you for your work.
I'd like to install your package but I encounter some problems.
If I try :  ``wp package install diggy/polylang-cli``
I get : ``Error: Invalid package``
And with : ``wp package install git@github.com:diggy/polylang-cli.git``
I get : ``PHP Fatal error:  require(): Failed opening required '/root/.wp-
cli/packages/vendor/diggy/polylang-cli/vendor/autoload.php'``.
What is the right way to do it ? Thank you very much.

**Comment by diggy** [comment]
@gbouteiller thank you for your interest in this package! I've been struggling with Behat not autoloading the commands. For now, as this package is still in alpha, I'm giving priority to the tests, hence [this line](https://github.com/diggy/polylang-cli/blob/master/command.php#L20). If you comment out that line in the package dir on your local machine (e.g. `/Users/username/.wp-cli/packages/vendor/diggy/polylang-cli/command.php`) you should be able to run the commands. Alternatively, you could download the package, and require it in your `wp-cli.local.yml` file. I know this is far from ideal, but I'm actively looking for a solution, and will ping you here when resolved.

**Comment by diggy** [comment]
@gbouteiller skipping autoloading for now, package should be installable with

`wp package install git@github.com:diggy/polylang-cli.git`

**Comment by gbouteiller** [comment]
@diggy Thank you very much!
