### ISSUE TITLE
There may be no Africans translation for trunk

### ISSUE THREAD

**Issue by szepeviktor** [diggy/polylang-cli#68]
This: https://github.com/diggy/polylang-cli/blob/master/features/lang.feature#L17
In action: https://travis-ci.org/diggy/polylang-cli/builds/240548989#L644

**Comment by szepeviktor** [comment]
Maybe I am wrong.
WP trunk (WordPress 4.9-alpha-40877) may have an inconsistent version number

```php
$wp_version = '4.9-alpha-40877';
```

**Comment by szepeviktor** [comment]
Oh! `af.zip`

There may be no [Africans translation](https://translate.wordpress.org/locale/af) for trunk!!

**Comment by diggy** [comment]
the plot thickens :)

**Comment by szepeviktor** [comment]
We could `behat --tags '~@skiptrunk'` and add `@skiptrunk` in this test.

**Comment by diggy** [comment]
or pick another language?

**Comment by szepeviktor** [comment]
May there's no translation at all for 4.9
See https://translate.wordpress.org/locale/de

**Comment by diggy** [comment]
testing against trunk out of curiosity, but not essential (therefore allowed to fail). Would you mind submitting a PR with the `@skiptrunk` tag?
